Revert "- Resolves the AttributeError: 'tuple' object has no attribute 'id' raised when MongoDB (and other"
This reverts commit 613220a16f99b9676759a40bfa2bd68354430e3b.